### PR TITLE
Pure Localization & Networking

### PR DESCRIPTION
**Pull request by christqoh**
🎶 It's Docker time, and there's no need to be afraid
At Docker time, we let in light and banish shade
And in our world of plenty, we can spread a smile of joy
Throw your arms around the world
At Docker time 🎶

Core improvements:
- now able to run pure localization on LEIA with visualization on remote maching
- Networking across several machines
- Documentation

Minor improvements:
- cleaned up our docker structure
- automatically installing net-tools (ifconfig)
- automatically getting latest roboy code

Learnings:
- we will from now on stick with pure localization syntax on 1.0.0 release
- no one touches /src/cartographer/ folder!

ToDo:
- fine-tune cartographer on data
- automatically copying our recorded data to docker (.pbstream for pure localization) to be able to have pure localization starting up automatically

### CODE REVIEW

**Review by jonas-kerber — APPROVED** [review]
nice and overseeable documentation through READMEs

**Comment by jonas-kerber** [comment]
BTW and off-topic: A song at the start of the pull request is a great way to start reviewing ;)

**Review by lennarthaller — APPROVED** [review]
Very cool that the visualization and docker work now. +1 For the documentation.

**Review by melkonyan — APPROVED** [review]
Everything looks good. I didn't run the code

**Pull request merged**
